In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('Preprocessed_Data.csv')
predictors = data.iloc[:, :7]
target = data.iloc[:, 7]
data.head()

Sex  Age  Height  Weight  Low Income  Lower Middle Income  \
0    1    5      75      17           1                    0   
1    0    4     101      13           1                    0   
2    0    4      71      17           1                    0   
3    0    3      81      13           0                    0   
4    0    1      79      16           0                    0   

   Upper Middle Income    Status  
0                    0  Stunting  
1                    0  Stunting  
2                    0  Stunting  
3                    1  Stunting  
4                    1  Stunting

In [3]:
print(predictors.head())
print(target.head())

   Sex  Age  Height  Weight  Low Income  Lower Middle Income  \
0    1    5      75      17           1                    0   
1    0    4     101      13           1                    0   
2    0    4      71      17           1                    0   
3    0    3      81      13           0                    0   
4    0    1      79      16           0                    0   

   Upper Middle Income  
0                    0  
1                    0  
2                    0  
3                    1  
4                    1  
0    Stunting
1    Stunting
2    Stunting
3    Stunting
4    Stunting
Name: Status, dtype: object


In [4]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(predictors, target, test_size = 0.2)

In [5]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 300)
model.fit(xtrain, ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [6]:
predict = model.predict(xtest)

In [7]:
predict

array(['Stunting', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Stunting', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Stunting', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Stunting', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Stunting', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Overweight', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Stunting', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Stunting', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Stunting', 'Overweight', 'Stunting', 'Stunting', 'Stunting',
       'Stunting', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Stunting', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Overweight', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Stunting', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Overweight', 'Stunting', 'Stunting', 'Stunting', 'Stunting',
       'Stunting', 'Stunting', 'Stunting', 'Stunting',

In [17]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(ytest, predict))
print(classification_report(ytest, predict))
print("Accuracy Of Our Model Is:-",accuracy_score(ytest, predict)*100, "%")

[[  4  12   0   0]
 [  6 140   0   0]
 [  1   4   0   0]
 [  0   1   0   0]]
              precision    recall  f1-score   support

  Overweight       0.36      0.25      0.30        16
    Stunting       0.89      0.96      0.92       146
 Underweight       0.00      0.00      0.00         5
     Wasting       0.00      0.00      0.00         1

   micro avg       0.86      0.86      0.86       168
   macro avg       0.31      0.30      0.31       168
weighted avg       0.81      0.86      0.83       168

Accuracy Of Our Model Is:- 85.71428571428571 %
